version: "3.4"

services:
  expenses-webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: expenses-webapp
    container_name: expenses-webapp
    command: "npm start"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      - REACT_APP_API_ADMIN_SECRET=${REACT_APP_API_ADMIN_SECRET}
      - PUBLIC_GITHUB_REPOSITORY=${PUBLIC_GITHUB_REPOSITORY}
      - PUBLIC_GITHUB_ACCOUNT_TOKEN=${PUBLIC_GITHUB_ACCOUNT_TOKEN}
    volumes:
      - ./webapp:/app

      # create an empty directory at `/app/node_modules` instead of using the previously
      # mounted `./webapp/node_modules` directory, so the host's `node_modules` ownership
      # doesn't pass to the container's user
      - /app/node_modules

      # Required by git to deploy to GitHub
      - ./.ssh:/root/.ssh
