version: "3.4"

services:
  expenses-webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: expenses-webapp
    container_name: expenses-webapp
    command: "npm start"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      - REACT_APP_SPLITWISE_API_BASE_URL=${REACT_APP_SPLITWISE_API_BASE_URL}
      - REACT_APP_MOCK_APIS=${REACT_APP_MOCK_APIS:-false}
      - REACT_APP_SPLITWISE_USER_EMAIL_ME=${SPLITWISE_USER_EMAIL_ME}
      - REACT_APP_SPLITWISE_USER_EMAIL_PARTNER=${SPLITWISE_USER_EMAIL_PARTNER}
    volumes:
      - ./webapp:/app

      # create an empty directory at `/app/node_modules` instead of using the previously
      # mounted `./webapp/node_modules` directory, so the host's `node_modules` ownership
      # doesn't pass to the container's user
      - /app/node_modules

  qr:
    build:
      context: ./qr
      dockerfile: Dockerfile
    image: qr
    container_name: qr
    volumes:
      - ./qr:/app
