#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset


SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

REPO_DIR="$( realpath "${SCRIPT_DIR}/.." )"


cd "${REPO_DIR}/"

podman compose --file .agent-env/docker-compose.yaml run --rm claude
